### ISSUE TITLE
IOError Bad file descriptor

### ISSUE THREAD

**Issue by dotSlashLu** [lavr/python-emails#116]
CentOS 6.8 2.6.32 
python 2.7.13
emails (0.5.15) installed via pip

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data/server/server/lib/mail.py", line 104, in send_status_real
  File "/data/server/server/lib/mail.py", line 104, in send_status_real
    send(to, u'[notice]-%s' % title, content, cc, attachs=[full_filename])
  File "/data/server/server/lib/mail.py", line 134, in send
    "port": config.port})
  File "/data/server/lib/python2.7/site-packages/emails/message.py", line 404, in send
    return smtp.sendmail(**params)
  File "/data/server/lib/python2.7/site-packages/emails/backend/smtp/backend.py", line 117, in sendmail
    msg=msg.as_string(),
  File "/data/server/lib/python2.7/site-packages/emails/message.py", line 337, in as_string
  File "/data/server/lib/python2.7/site-packages/emails/message.py", line 337, in as_string
    r = to_native(self.build_message(message_cls=message_cls).as_string())
  File "/data/server/lib/python2.7/site-packages/emails/message.py", line 305, in build_message
  File "/data/server/lib/python2.7/site-packages/emails/message.py", line 305, in build_message
    part = f.mime
  File "/data/server/lib/python2.7/site-packages/emails/store/file.py", line 143, in mime
  File "/data/server/lib/python2.7/site-packages/emails/store/file.py", line 143, in mime
    p.set_payload(to_bytes(self.data))
  File "/data/server/lib/python2.7/site-packages/emails/store/file.py", line 57, in get_data
    return _data.read()
IOError: [Errno 9] Bad file descriptor
close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor[Errno 9] Bad file descriptor
```

**Comment by lavr** [comment]
I suppose you try to reference file by its path `full_filename`
Use file object instead: `open(full_filename, 'rb')`

**Comment by dotSlashLu** [comment]
Thanks @lavr. This nice project really helped me a lot.
