### ISSUE TITLE
Syntax error in ez_setup.py during email package installation

### ISSUE THREAD

**Issue by Px8Studio** [lavr/python-emails#172]
When attempting to install the email package using pip, an error occurs due to a syntax error in the ez_setup.py file. The error message is:

- Traceback (most recent call last):
  File "<masked>\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
    main()
  File "<masked>\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<masked>\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^
  File "<masked>\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<masked>\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "<masked>\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
  File "<masked>\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 3, in <module>
  File "<masked>\Temp\pip-install-sjllk17b\email_9422df62f5374c5bb78d15112b4d0ff5\ez_setup.py", line 91
    except pkg_resources.VersionConflict, e:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

The error occurs in the ez_setup.py file, specifically in line 91, where there is a syntax error in the except statement.

I have tried updating pip, reinstalling the email package, and inspecting the ez_setup.py file, but the issue persists.

Additional information:

Pip version: 24.0
Python version: 3.12.2
Operating system: Windows 11 Pro

**Comment by lavr** [comment]
Hi!
This project (python-emails) has no ez_setup.py file.
