### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by Garito** [lavr/python-emails#39]
Hi!!

Could anyone explain why is this raising a UnicodeEncodeError??
You will see: the text that raises the error, its encoding and the full traceback (if I dosn't make a mistake)
Thanks!!!!

INFO in utils [/Users/garito/TimeFounder/App/0.2/TimeFounder/utils.py:35]:
Your email has been used to ask for an invitation on https://app.timefounder.com.
To register your account click in the link below.
http://localhost:5000/users/signUp?code=ebc601ee-d0a6-11e4-b825-0023dfa2a3b4

If you are not ask for an invitation, please ignore this email

INFO in utils [/Users/garito/TimeFounder/App/0.2/TimeFounder/utils.py:36]:
<type 'unicode'>

127.0.0.1 - - [22/Mar/2015 16:22:08] "GET /users/send_invitation?email=garito%2Bhome%40gmail.com HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/garito/TimeFounder/App/0.2/TimeFounder/__init__.py", line 82, in __call__
    return self.app(environ, start_response)
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/Users/garito/TimeFounder/App/0.2/Users/__init__.py", line 166, in send_invitation
    send_mail(title, data, recipients)
  File "/Users/garito/TimeFounder/App/0.2/TimeFounder/utils.py", line 49, in send_mail
    sended[recipientTuple] = msg.send(to=recipientTuple)
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/flask_emails/message.py", line 63, in send
    return super(Message, self).send(smtp=smtp_options, **kw)
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/emails/message.py", line 352, in send
    response = smtp.sendmail(**params)
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/emails/backend/smtp/backend.py", line 118, in sendmail
    msg=to_bytes(msg.as_string(), 'utf-8'),
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/emails/message.py", line 423, in as_string
    return self.dkim_sign_string(to_bytes(self.build_message(message_cls=message_cls).as_string()))
  File "/Users/garito/TimeFounder/App/0.2/env/lib/python2.7/site-packages/emails/utils.py", line 152, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/generator.py", line 83, in flatten
    print >> self._fp, ufrom
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/generator.py", line 115, in _write
    if meth is None:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/generator.py", line 164, in _write_headers
    print >> self._fp, Header(
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 26: ordinal not in range(128)

**Comment by lavr** [comment]
Will be nice to see message headers.

Please add `print msg.as_message().items()` to file /Users/garito/TimeFounder/App/0.2/TimeFounder/utils.py before line 49 and show us output.

**Comment by Garito** [comment]
[('Content-Type', u'multipart/mixed'), ('MIME-Version', '1.0'), (u'Date', 'Sun, 22 Mar 2015 22:41:56 +0100'), (u'Subject', lu'[T:F] Enlace a la invitaci\xf3n'), (u'From', u'Time Founder butler <butler at timefounder.com>')]

**Comment by lavr** [comment]
Problem in subject header I guess - it may not contain non-ascii chars. 
But I have no idea why they are here.
emails.Message encode headers by default:

    $ python -c "import emails; msg=emails.Message(html='...'); msg.subject=u'[T:F] Enlace a la invitaci\xf3n'; print msg.as_message().items()"
    [..., (u'Subject', '=?utf-8?b?W1Q6Rl0gRW5sYWNlIGEgbGEgaW52aXRhY2nDs24=?=')]

Can you show parts of your code where you generate Message object and set it's subject ?

**Comment by Garito** [comment]
```python
def send_mail(title, message, recipients):
	if isinstance(message, dict):
		template = current_app.jinja_env.get_template(message.pop('template'))
		
		current_app.logger.info(template.render(**message))
		
		msg = Message(subject=title, text=template.render(**message),
									mail_from=(current_app.config['SENDER_NICK'],
														 current_app.config['EMAIL_SENDER']))
		
		current_app.logger.info(msg.as_message().items())
		
		used = []
		sended = {}
		for recipient in recipients:
			recipientTuple = (recipient.nick, recipient.email) if 'nick' in recipient else recipient
			
			if recipientTuple not in used:
				used.append(recipientTuple)
				sended[recipientTuple] = msg.send(to=recipientTuple)
				
		return sended
´´´
Sorry for not comment more, I have broken my clavicle and its hard to me to write with one hand

Thanks by the way

**Comment by Garito** [comment]
```python
def send_invitation():
  model = current_app.factory('Invitation')
  try:
    invitation = model.get_by_field("email.raw", request.args.get('email')).next()
  except StopIteration:
    flash(_("This invitation is not valid"), "danger")
    return redirect(url_for('.users'))
  
  title = _("[T:F] Invitation link")
  data = {'template': 'notifications/invitation.txt',
          'url': url_for('.signUp', code=invitation.code, _external = True)}
  recipients = [invitation.email]
  send_mail(title, data, recipients)

  invitation.sender = g.user.email
  invitation.sended = datetime.now()
  invitation.updateRole(invitation._id, 'send')
  flash(_("The invitation has been send!"), "success")
  return redirect(request.referrer)
```

Where I send the mails

**Comment by lavr** [comment]
`_` is `gettext.gettext` ?

**Comment by Garito** [comment]
No is lazy_gettext:
from flask.ext.babel import lazy_gettext as _

**Comment by Garito** [comment]
mmm with get text seems to work...
will try more tests

**Comment by Garito** [comment]
Seems good to me: thanks a lot

**Comment by lavr** [comment]
emails 0.4.11 with lazy_gettext support is [on pypi](https://pypi.python.org/pypi/emails/0.4.11)

**Comment by Garito** [comment]
What difference or affectation has this??

**Comment by lavr** [comment]
Now Message should correctly encode lazy_gettext object in subject.

**Comment by Garito** [comment]
Ok, will update the library and comment if I have an issue

Thank you!!

**Comment by lavr** [comment]
Your feedback will be appreciated

**Comment by Garito** [comment]
Seems it works fine
Will notify you if any other issue apears

Nice work, thanks

**Comment by arisliang** [comment]
Is Unicode not supported?
