### ISSUE TITLE
Silent fail if port param is Unicode string

### ISSUE THREAD

**Issue by rasa** [lavr/python-emails#85]
In Python 2.7.13 on Windows 7., running v0.5.13, the program:
````
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import emails

SMTP_USER = 'ex@gmail.com'
SMTP_PASS = 'abracadabera'
SMTP_HOST = 'smtp.gmail.com'
SMTP_PORT = '587'
SMTP_FROM = 'ex+from@gmail.com'
SMTP_TO = 'ex+to@gmail.com'

m = emails.Message(text='body', subject='subject', mail_from=SMTP_FROM)
smtp={'debug': 1, 'host':SMTP_HOST, 'port': SMTP_PORT, 'tls': True, 'user': SMTP_USER, 'password': SMTP_PASS}
response = m.send(to=SMTP_TO, smtp=smtp)
print(response)
````
produces no logs, but this result:
````
<emails.backend.SMTPResponse status_code=None status_text=None>
````
If I change
````
SMTP_PORT = '587'
````
to
````
SMTP_PORT = 587
````
or
````
SMTP_PORT = str('587')
````
it works fine.

**Comment by lavr** [comment]
Actually it's exception come from smtplib:

```
Python 2.7.10 (default, Feb  6 2017, 23:53:20)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import smtplib
>>> smtplib.SMTP_SSL(host='smtp.gmail.com', port=u'587')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 796, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 801, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.error: getaddrinfo() argument 2 must be integer or string
```

**Comment by lavr** [comment]
But python-emails should handle such exception properly

**Comment by rasa** [comment]
Thank you!
